console.log($("body").text())
console.log($("body").html())
//alert()
$("p").text("HOLA MUNDO")
//alert()
$("p").html("<b>HOLA MUNDO</b>")
console.log($("input").val())
$("input").val(32)
//$("p").css("background", "red")
//$("p").css("color", "white")
//$("p").addClass("verde")
//$("p").removeClass("verde")
//$("p").addClass("amarillo")
//alert()
//$("p").toggleClass("amarillo")
//alert()
//$("p").toggleClass("amarillo")
$("p").fadeOut(1000)
$("p").fadeIn(1000)
$("p").slideUp(1000)
$("p").slideDown(1000)